export const ISLOGIN = 'ISLOGIN';
export const ADD_CURNT_WEATHER = 'ADD_CURNT_WEATHER';
export const ADD_SEARCH_HISHORY = 'ADD_SEARCH_HISTORY';
export const ADD_NEAREST_WEATHER = 'ADD_NEAREST_WEATHER';
export const REMOVE_SEARCH_HISTORY = 'REMOVE_SEARCH_HISTORY';
